### ISSUE TITLE
YNAB::SaveTransaction amount = Integer instead of Float?

### ISSUE THREAD

**Issue by therod** [ynab/ynab-sdk-ruby#22]
Hey there!

The [Documentation](https://github.com/ynab/ynab-sdk-ruby/blob/master/docs/SaveTransaction.md) specifies that the amount parameter should be a float. If I provide a float in my request I get a `YNAB::ApiError: Bad Request` error which I found strange.

Upon further investigation and playing with the API over at [api.youneedabudget.com](https://api.youneedabudget.com/v1#/Transactions/createTransaction) it seems that the API requires an Integer not a Float.

```json
{
  "error": {
    "id": "400",
    "name": "bad_request",
    "detail": "{\"amount\":[\"must be an integer\"],\"date\":[\"must be an ISO formatted date\"]}"
  }
}
```

I'm currently writing an integration for a Swiss bank – but only being able to write Integers via the API would be a major letdown. 😔

Thanks for your time.

Best,
Rodrigo

**Comment by bradymholt** [comment]
@therod The API only allows integers but we use a format called [milliunits](https://api.youneedabudget.com/#formats) which allows you to specify a decimal value.  For example, to specify 11.32 you would use 11320.  The docs on the client repo here should not be showing Float and we'll get that fixed.  Thank you.

**Comment by therod** [comment]
Got it! Thanks for clearing this up @bradymholt 🙌
