### ISSUE TITLE
Add support for internal transactions

### ISSUE THREAD

**Issue by schurig** [ynab/ynab-sdk-ruby#28]
Hi, I've just read the great news that now internal transactions are supported.

I was checking the documentation and is it correct that the only thing that needs to be changed here is this comment?

https://github.com/ynab/ynab-sdk-ruby/blob/6d384b92cea03643dc2478d3e160f8af951d13d3/lib/ynab/models/save_transaction.rb#L24 😍

**Comment by bradymholt** [comment]
Fixed by #30
