### ISSUE TITLE
months.get_month_category_by_id does not exist

### ISSUE THREAD

**Issue by JohnLegrandRichards** [ynab/ynab-sdk-ruby#62]
Why is this defined in the readme

months.get_month_category_by_id(budget_id, month, category_id)

When it doesnt even exist in the code

**Comment by JohnLegrandRichards** [comment]
Actually it looks like it is just under the incorrect grouping. I will fix it

**Comment by bradymholt** [comment]
👍 

Moved here: https://github.com/ynab/ynab-sdk-ruby/commit/70d93b4a07e1eae1251ae8e8636bd8578f74e1b8
