### ISSUE TITLE
PHP SDK

### ISSUE THREAD

**Issue by jerrylopez** [ynab/ynab-sdk-ruby#7]
Hey @bradymholt! I see that you guys recently put together this SDK for Ruby. Will you guys be creating an SDK for PHP?

**Comment by bradymholt** [comment]
@jerrylopez A PHP client is not on the immediate horizon.  If you end up building one yourself please let us know as we might, at some point, feature third-party clients somewhere in the API documentation.

We used [Swagger CodeGen](https://swagger.io/swagger-codegen/) as a starting point for the JavaScript and Ruby clients and that might be a route to use for a quicker start.  If you decide to go that route, here is the Swagger spec for the API, which CodeGen would need: https://api.youneedabudget.com/papi/spec-v1-swagger.json.

Good luck and thanks for your interest in the API!

**Comment by jerrylopez** [comment]
@bradymholt gotcha! Got it generated with CodeGen 👍 
https://github.com/jerrylopez/ynab-sdk-php

**Comment by bradymholt** [comment]
@jerrylopez Awesome!  I'll add this to our own list of 3rd party libraries which we will probably list somewhere in the docs at some point.  By the way, I love your initial commit message over there 😄
