### ISSUE TITLE
Is the SaveTransaction class unused?

### ISSUE THREAD

**Issue by jordancrawfordnz** [ynab/ynab-sdk-ruby#76]
Hi - I recently upgraded to version 3.2 from a 2.x version. I had code which was using SaveTransaction with the create transaction API (https://github.com/ynab/ynab-sdk-ruby/blob/main/docs/TransactionsApi.md#create_transaction).

I noticed that the SaveTransaction class and it's docs still exists but isn't referenced in `lib/ynab.rb` so cannot be loaded.

Is the class meant to be loadable? Or is it meant to be removed?

I switched my code over to use NewTransaction and so far it's working as intended.

**Comment by bradymholt** [comment]
Ah, you're right, this class is no longer in use.  `NewTransaction` is the class you'll want.  I have a PR here: https://github.com/ynab/ynab-sdk-ruby/pull/79 to fix this.  Thanks for letting us know.
