### ISSUE TITLE
Max length for `memo` and `payee_name` does not match what YNAB allows

### ISSUE THREAD

**Issue by davidstosik** [ynab/ynab-sdk-ruby#77]
Hi there! 👋🏻 
First I've got to state again how happy I am using YNAB and the API for my own workflow, this is working great!

I recently noticed that some field maximum lengths might not match the actual length limits when using the YNAB web client.

In short, the OpenAPI spec file specifies a `maxLength` for `payee_name` and `memo` fields of respectively 50 and 200, but it's been possible for a long time to create transactions with longer payee name and memo. (I just created a transaction with a 10,000-character long memo!)

I think this issue is very similar to this other issue I opened back in February last year: [Validation error on API response for TransactionDetail#import_payee_name](https://github.com/ynab/ynab-sdk-ruby/issues/65), and that it could get a similar fix ([Remove unnecessary maxLength validation for import payee fields](https://github.com/ynab/ynab-sdk-ruby/pull/66)).

One thing I noticed that might have not been the case last year, is that even if I remove the validations Ruby-side, the API actually responds with an error too:
```json
{"error":{"id":"400","name":"bad_request","detail":"memo is too long (maximum is 200 characters) (index: 19), memo is too long (maximum is 200 characters) (index: 36), memo is too long (maximum is 200 characters) (index: 37)"}}
```
I could imagine this is happening if YNAB's API server code is also generated with the OpenAPI Generator, based on the same OpenAPI spec. In this case, the fix would require not only a new version of this gem but also an update of YNAB's server-side API code.

Hope this makes sense, but feel free to let me know if you need more details! 🙏🏻

**Comment by bradymholt** [comment]
@davidstosik thanks for the feedback!

The API does indeed have smaller limits for some fields; this is intentional and by design.  Having said that, if you have a specific use case for increasing these a bit, we can consider that.

**Comment by davidstosik** [comment]
@bradymholt thanks for the reply!

As for a use case, you can check my previous issue that I linked in the description above: basically, it's impossible to write a script that fetches existing transactions, changes them then saves them again, since you might be fetching transactions that were created in the UI and will appear invalid from the API.

**Comment by bradymholt** [comment]
Ah, I see.  Thanks for the context.  As I mentioned, we intentionally limit these in the API to prevent abuse.  Is there a limit we could increase it to (short of the limit the apps allows) that would allow you to proceed, even if you needed to trim in some cases when saving a transaction from the API?

**Comment by davidstosik** [comment]
@bradymholt Sorry it took me some time to get back to you.
I took a look at my whole budget:
```rb
# frozen_string_literal: true

require "ynab"

puts "Fetching data..."

ynab_api = YNAB::API.new(ENV["YNAB_ACCESS_TOKEN"])
budget = ynab_api.budgets.get_budgets.data.budgets.sort_by(&:last_modified_on).last
transactions = ynab_api.transactions.get_transactions(budget.id).data.transactions

puts <<~OUTPUT
  Fetched #{transactions.count} transactions.
  Three longest memo sizes: #{transactions.filter_map(&:memo).map(&:length).uniq.max(3).join(", ")}
  Three longest payee name sizes: #{transactions.filter_map(&:payee_name).map(&:length).uniq.max(3).join(", ")}
OUTPUT
```

```
Fetching data...
Fetched 5225 transactions.
Three longest memo sizes: 273, 200, 199
Three longest payee name sizes: 100, 98, 92
```

So I've got old transactions in my budget with memo and payee name that exceed the current validations. (I'm actually surprised the YNAB gem did not fail to load the data, as it does with invalid flag colors, [here](https://github.com/ynab/ynab-sdk-ruby/issues/81). 😅)

I'm writing an import script that allows me to import into YNAB transactions from my various Japanese bank account. (There's no account linking here!)
On of the specificities is using a separate account for Amazon transactions, where I'd like to use the product name as memo.
That's where I hit a wall, as some product names can exceed the 200-character limit easily.
The payee name is less of a problem I guess.

I understand that removing the limits would favor abuse, but do you think that it would be possible to:
1. augment the current limits for memo and payee name to respectively 500 and 200 characters?
2. maybe add those limitations to the UI as well, preventing discrepancy between UI and API? (Currently, how would I save a transaction that I fetched using the API then modified locally, if it has an invalid memo?)

**Comment by bradymholt** [comment]
@davidstosik - Thanks for the feedback.  I understand the friction that can be caused by having different limits on the clients and the API.  I'll raise this internally to see about some better alignment there.  In the meantime, we can increase the limits on allowed by the server for `memo` and payee_name` to 500 and 200, respectively.  We'll work on a server change to get this out.

**Comment by bradymholt** [comment]
Update - This increase in limit is scheduled to ship early next week.

**Comment by davidstosik** [comment]
@bradymholt thank you very much!

**Comment by davidstosik** [comment]
@bradymholt May I ask for an update on this? (Nothing urgent, just wondering if anything went out, since I don't see a new release of the gem.) 🙏🏻

**Comment by bradymholt** [comment]
@davidstosik - The server change (1.72.1) went out back in July but we didn't mention on the [release notes](https://api.ynab.com/#v1.72.0) since it was a very minor patch.  Honestly, I didn't think a new client would be needed for this change but now I see that indeed there is a some validation logic that checks the length against the spec.  I'll cut a new release here in just a minute!  Thanks for the ping.
